### PR TITLE
feat: new black ui

### PR DESCRIPTION
**Pull request by aLIEzsss4**

### CODE REVIEW

**Review by noyyyy — CHANGES_REQUESTED** [review]
Remove `pnpm-lock.yaml` change.

**Comment by noyyyy** [comment]
Also, the branch has some this branch has some commits that have been merged into the develop branch. You should checkout from latest develop branch next time.

image

**Comment by aLIEzsss4** [comment]
> Remove `pnpm-lock.yaml` change.

Is it possible to ignore the lock file and have it generated automatically through Git hooks, CI pipelines, or the pnpm generate-lockfile command?

**Review by noyyyy — APPROVED** [review]

**Comment by noyyyy** [comment]
> > Remove `pnpm-lock.yaml` change.
> 
> Is it possible to ignore the lock file and have it generated automatically through Git hooks, CI pipelines, or the pnpm generate-lockfile command?



> `pnpm-lock.yaml`

Not necessary. `pnpm-lock.yaml` is generate locally when you add new packages. Just use https to finish git clone and check your local settings.

**Pull request merged**
